### PR TITLE
Init

### LINKED ISSUE #2: Init Observable
Init observable in repo

### LINKED ISSUE #3: Load data into Observable
Inladen data in Observable in deftige structuur.

### PR DESCRIPTION
**Pull request by jbvilla**
Init observablehq

fixes #2 
fixes #3

### CODE REVIEW

**Review by milachae — APPROVED** [review]
Works good!

Small remarks, can be changed:
- No need to include the example anymore
- I do think we don't really need an extra subdirectory 'fietstellingen'

**Comment by milachae** [comment]
@jbvilla 

I get following error when I run the `preprocessingData.js` script.

```
node:internal/process/esm_loader:100
    internalBinding('errors').triggerUncaughtException(
                              ^

[Error: ENOENT: no such file or directory, open 'docs/data.csv'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'docs/data.csv'
}

Node.js v19.6.1
```

Is this normal?

**Review by milachae — CHANGES_REQUESTED** [review]
Static data files should be placed in data/ folder.
Maybe do this relative to the location of the script, this way, it will not matter where you execute the script. You can use `__dirname` for this.

Also see my previous comment.

**Comment by jbvilla** [comment]
> Works good!
> 
> Small remarks, can be changed:
> - No need to include the example anymore
> - I do think we don't really need an extra subdirectory 'fietstellingen'

De voorbeelden zijn voor rap nog iets te zien, dit kan later worden verwijderd.

Die extra sub dir moest omdat anders geen observable init kon gedaan worden. Omdat we al andere files hadden en zo kunnen we een overzicht houden zoals die databeschrijving dat moet niet in de observable project komen.

**Comment by jbvilla** [comment]
> Static data files should be placed in data/ folder.
> Maybe do this relative to the location of the script, this way, it will not matter where you execute the script. You can use `__dirname` for this.
> 
> Also see my previous comment.

Nee de voorbeeld files waren ook in die folder, die worden automatisch geplaats op de juiste plaats in de build dus die staat juist.

**Comment by milachae** [comment]
> > Static data files should be placed in data/ folder.
> > Maybe do this relative to the location of the script, this way, it will not matter where you execute the script. You can use `__dirname` for this.
> > Also see my previous comment.
> 
> Nee de voorbeeld files waren ook in die folder, die worden automatisch geplaats op de juiste plaats in de build dus die staat juist.

@jbvilla , You wrote the follow in your README.md:

> **`docs/data`** - You can put [data loaders](https://observablehq.com/framework/loaders) or static data files anywhere in your source root, but we recommend putting them here.

So I do think it make sense to place the static data files in the data directory.

**Comment by jbvilla** [comment]
> > > Static data files should be placed in data/ folder.
> > > Maybe do this relative to the location of the script, this way, it will not matter where you execute the script. You can use `__dirname` for this.
> > > Also see my previous comment.
> > 
> > Nee de voorbeeld files waren ook in die folder, die worden automatisch geplaats op de juiste plaats in de build dus die staat juist.
> 
> @jbvilla , You wrote the follow in your README.md:
> 
> > **`docs/data`** - You can put [data loaders](https://observablehq.com/framework/loaders) or static data files anywhere in your source root, but we recommend putting them here.
> 
> So I do think it make sense to place the static data files in the data directory.

Die readme is automatisch gegenereerd, in de tutorial stonden de csv bestanden in de docs

**Review by milachae — APPROVED** [review]

**Pull request merged**
